version: "2"

issues:
  exclude-rules:
    - path_prefix: "internal/app/database/migration"

linters-settings:
  govet:
    enable:
      - shadow
  goimports:
    local-prefixes: github.com/aburizalpurnama/travel
  errcheck:
    check-blank: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - goimports
    - gofmt
    - bodyclose
    - gosimple
    - ineffassign
    - typecheck
