issues:
  exclude:
    - ".*_test.go$"
    - ".*.sql$"
    - "internal/app/database/migration/.*.go$"

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable:
      - shadow
  goimports:
    local-prefixes: github.com/aburizalpurnama/travel

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - goimports
    - gofmt
    - bodyclose     # Wajib untuk API
    - gosimple
    - ineffassign
    - typecheck
