issues:
  exclude-rules:
    - path: "internal/app/database/migration/"
      linters:
        - errcheck
        - govet
        - staticcheck
        - unused
        - goimports
        - gofmt
        - bodyclose
        - gosimple
        - ineffassign
        - typecheck

linters-settings:
  govet:
    enable:
      - shadow
  goimports:
    local-prefixes: github.com/aburizalpurnama/travel
  errcheck:
    check-blank: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - goimports
    - gofmt
    - bodyclose
    - gosimple
    - ineffassign
    - typecheck
