version: "2"

linters:
  # Disable all default linters, then enable only the ones explicitly listed below.
  default: none

  # Enabled linters (formatters like gofmt/goimports are now in the 'formatters' section).
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - bodyclose
    - ineffassign
    # gosimple is often redundant with staticcheck. Uncomment if specifically needed:
    # - gosimple

  # Paths or directories to exclude from linter analysis.
  exclusions:
    paths:
      - internal/app/database/migration

  # Specific configuration for enabled linters.
  settings:
    govet:
      # In schema v2, use 'enable: - shadow' to check for variable shadowing.
      enable:
        - shadow

formatters:
  # Format checkers (gofmt, goimports, gofumpt, gci, etc.) are configured in this section.
  enable:
    - gofmt
    - goimports

  # Specific settings for formatters (uncomment if needed):
  # settings:
  #   gofmt:
  #     simplify: false
  #   goimports:
  #     local-prefixes:
  #       - github.com/yourorg/yourrepo

run:
  # Target Go version for analysis tools to ensure consistency, make it same with the version in your go.mod.
  go: "1.25.1"
  timeout: 5m
