version: "2"

linters:
  exclusions:
    paths:
      - internal/app/database/migration
  settings:
    govet:
      enable:
        - shadow
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - goimports
    - gofmt
    - bodyclose
    - gosimple
    - ineffassign
