CREATE SCHEMA IF NOT EXISTS "core";
CREATE SCHEMA IF NOT EXISTS "user";
CREATE SCHEMA IF NOT EXISTS "transaction";

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TYPE IF EXISTS "user".users_role_enum;
CREATE TYPE "user".users_role_enum AS ENUM ('customer','muthawif');

DROP TYPE IF EXISTS "user".admins_role_enum;
CREATE TYPE "user".admins_role_enum AS ENUM ('agent','admin','fin_inst');

DROP TYPE IF EXISTS "user".customer_gender_enum;
CREATE TYPE "user".customer_gender_enum AS ENUM ('male','female');

DROP TYPE IF EXISTS "user".admin_role_level_enum;
CREATE TYPE "user".admin_role_level_enum AS ENUM ('admin','super_admin');

DROP TYPE IF EXISTS transaction.bookings_installment_request_status_enum;
CREATE TYPE transaction.bookings_installment_request_status_enum AS ENUM ('requested','approved');

DROP TYPE IF EXISTS transaction.bookings_status_enum;
CREATE TYPE transaction.bookings_status_enum AS ENUM ('booked','confirmed','on-trip','done','canceled','refunded');

DROP TYPE IF EXISTS transaction.bookings_payment_status_enum;
CREATE TYPE transaction.bookings_payment_status_enum AS ENUM ('unpaid','dp','paid');

DROP TYPE IF EXISTS core.refunds_status_enum;
CREATE TYPE core.refunds_status_enum AS ENUM ('requested','approved','rejected','processed','completed');

DROP TYPE IF EXISTS core.reschedules_status_enum;
CREATE TYPE core.reschedules_status_enum AS ENUM ('requested','approved','rejected','processed');

CREATE TABLE IF NOT EXISTS "user"."users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_on" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_by" jsonb NOT NULL DEFAULT ('{"user_uid": "SYSTEM", "user_name": "SYSTEM"}')::jsonb,
  "modified_on" timestamptz DEFAULT NULL,
  "modified_by" jsonb DEFAULT NULL,
  "deleted_on" timestamptz DEFAULT NULL,
  "full_name" varchar(255) NOT NULL,
  "gender" "user"."customer_gender_enum" NOT NULL,
  "email" varchar(320) DEFAULT NULL,
  "phone" varchar(50) NOT NULL,
  "password_hash" varchar(255) DEFAULT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "verified_by" jsonb DEFAULT NULL,
  "role" "user"."users_role_enum" NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_uid_active ON "user"."users" ("uid") WHERE "deleted_on" IS NULL;

CREATE TABLE IF NOT EXISTS "core"."products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_on" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_by" jsonb NOT NULL DEFAULT ('{"user_uid": "SYSTEM", "user_name": "SYSTEM"}')::jsonb,
  "modified_on" timestamptz DEFAULT NULL,
  "modified_by" jsonb DEFAULT NULL,
  "deleted_on" timestamptz DEFAULT NULL,
  "name" varchar(255) NOT NULL,
  "description" text DEFAULT NULL,
  "price" decimal(18,2) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_products_uid_active ON "core"."products" ("uid") WHERE "deleted_on" IS NULL;

CREATE TABLE IF NOT EXISTS "transaction"."bookings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_on" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_by" jsonb NOT NULL DEFAULT ('{"user_uid": "SYSTEM", "user_name": "SYSTEM"}')::jsonb,
  "modified_on" timestamptz DEFAULT NULL,
  "modified_by" jsonb DEFAULT NULL,
  "deleted_on" timestamptz DEFAULT NULL,
  "code" varchar(100) NOT NULL,
  "date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "product_id" int DEFAULT NULL,
  "product_name" varchar(255) DEFAULT NULL,
  "user_id" int NOT NULL,
  "user_full_name" varchar(255) NOT NULL,
  "total_qty" int NOT NULL,
  "total_amount" decimal(18,2) NOT NULL,
  "status" "transaction"."bookings_status_enum" NOT NULL DEFAULT 'booked',
  "payment_status" "transaction"."bookings_payment_status_enum" NOT NULL DEFAULT 'unpaid',
  "total_payment" decimal(18,2) NOT NULL DEFAULT 0,
  "max_payment_time" timestamptz DEFAULT NULL,
  CONSTRAINT fk_bookings_product_id FOREIGN KEY ("product_id") REFERENCES "core"."products" ("id"),
  CONSTRAINT fk_bookings_user FOREIGN KEY ("user_id") REFERENCES "user"."users" ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_bookings_uid_active ON "transaction"."bookings" ("uid") WHERE "deleted_on" IS NULL;
