CREATE SCHEMA IF NOT EXISTS "core";
CREATE SCHEMA IF NOT EXISTS "user";
CREATE SCHEMA IF NOT EXISTS "transaction";

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TYPE IF EXISTS "user".users_role_enum;
CREATE TYPE "user".users_role_enum AS ENUM ('customer','muthawif');

DROP TYPE IF EXISTS "user".admins_role_enum;
CREATE TYPE "user".admins_role_enum AS ENUM ('agent','admin','fin_inst');

DROP TYPE IF EXISTS "user".customer_gender_enum;
CREATE TYPE "user".customer_gender_enum AS ENUM ('male','female');

DROP TYPE IF EXISTS "user".admin_role_level_enum;
CREATE TYPE "user".admin_role_level_enum AS ENUM ('admin','super_admin');

DROP TYPE IF EXISTS transaction.bookings_installment_request_status_enum;
CREATE TYPE transaction.bookings_installment_request_status_enum AS ENUM ('requested','approved');

DROP TYPE IF EXISTS transaction.bookings_status_enum;
CREATE TYPE transaction.bookings_status_enum AS ENUM ('booked','confirmed','on-trip','done','canceled','refunded');

DROP TYPE IF EXISTS transaction.bookings_payment_status_enum;
CREATE TYPE transaction.bookings_payment_status_enum AS ENUM ('unpaid','dp','paid');

DROP TYPE IF EXISTS core.refunds_status_enum;
CREATE TYPE core.refunds_status_enum AS ENUM ('requested','approved','rejected','processed','completed');

DROP TYPE IF EXISTS core.reschedules_status_enum;
CREATE TYPE core.reschedules_status_enum AS ENUM ('requested','approved','rejected','processed');

CREATE TABLE IF NOT EXISTS "user"."users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_on" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_by" jsonb NOT NULL DEFAULT ('{"user_uid": "SYSTEM", "user_name": "SYSTEM"}')::jsonb,
  "modified_on" timestamptz DEFAULT NULL,
  "modified_by" jsonb DEFAULT NULL,
  "deleted_on" timestamptz DEFAULT NULL,
  "checksum" varchar DEFAULT NULL,
  "first_name" varchar(100) NOT NULL,
  "middle_name" varchar(100) DEFAULT NULL,
  "last_name" varchar(100) DEFAULT NULL,
  "full_name" varchar(255) NOT NULL,
  "gender" "user"."customer_gender_enum" NOT NULL,
  "nik" varchar(30) DEFAULT NULL,
  "passport_no" varchar(100) DEFAULT NULL,
  "passport_expires_on" date DEFAULT NULL,
  "nationality" varchar(100) DEFAULT 'Indonesia',
  "dob" date DEFAULT NULL,
  "email" varchar(320) DEFAULT NULL,
  "phone" varchar(50) NOT NULL,
  "arab_saudi_phone" varchar(50) DEFAULT NULL,
  "password_hash" varchar(255) DEFAULT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_verified" boolean NOT NULL DEFAULT false,
  "verified_by" jsonb DEFAULT NULL,
  "role" "user"."users_role_enum" NOT NULL,
  "preferred_language" varchar(10) DEFAULT 'id',
  "preferred_currency" varchar(10) DEFAULT 'IDR',
  "metadata" jsonb DEFAULT ('{}'::jsonb)
);

CREATE TABLE IF NOT EXISTS "core"."products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_on" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_by" jsonb NOT NULL DEFAULT ('{"user_uid": "SYSTEM", "user_name": "SYSTEM"}')::jsonb,
  "modified_on" timestamptz DEFAULT NULL,
  "modified_by" jsonb DEFAULT NULL,
  "deleted_on" timestamptz DEFAULT NULL,
  "checksum" varchar DEFAULT NULL,
  "name" varchar(255) NOT NULL,
  "desc" text DEFAULT NULL,
  "departure_city" varchar(200) DEFAULT NULL,
  "duration_days" int DEFAULT NULL,
  "transportations" jsonb DEFAULT NULL,
  "accommodations" jsonb DEFAULT NULL,
  "facilities" jsonb DEFAULT NULL,
  "itinerary" jsonb DEFAULT NULL,
  "payment_methods" jsonb NOT NULL,
  "prices" jsonb DEFAULT NULL,
  "lowest_price" decimal(18,2) DEFAULT NULL,
  "lowest_price_disc" decimal(18,2) DEFAULT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_recommended" boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "transaction"."bookings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_on" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_by" jsonb NOT NULL DEFAULT ('{"user_uid": "SYSTEM", "user_name": "SYSTEM"}')::jsonb,
  "modified_on" timestamptz DEFAULT NULL,
  "modified_by" jsonb DEFAULT NULL,
  "deleted_on" timestamptz DEFAULT NULL,
  "checksum" varchar DEFAULT NULL,
  "logs" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "code" varchar(100) NOT NULL,
  "date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "product_id" int DEFAULT NULL,
  "product_name" varchar(255) DEFAULT NULL,
  "product_batch" int DEFAULT NULL,
  "product_prices" jsonb NOT NULL,
  "duration_days" int DEFAULT NULL,
  "transportations" jsonb DEFAULT NULL,
  "accommodations" jsonb DEFAULT NULL,
  "facilities" jsonb DEFAULT NULL,
  "itinerary" jsonb DEFAULT NULL,
  "user_id" int NOT NULL,
  "user_full_name" varchar(255) NOT NULL,
  "passangers" jsonb DEFAULT NULL,
  "details" jsonb DEFAULT NULL,
  "total_qty" int NOT NULL,
  "total_amount" decimal(18,2) NOT NULL,
  "payment_method" jsonb NOT NULL,
  "is_installment" boolean NOT NULL DEFAULT false,
  "installment_request_documents" jsonb DEFAULT NULL,
  "installment_request_status" "transaction"."bookings_installment_request_status_enum" DEFAULT NULL,
  "status" "transaction"."bookings_status_enum" NOT NULL DEFAULT 'booked',
  "payment_status" "transaction"."bookings_payment_status_enum" NOT NULL DEFAULT 'unpaid',
  "total_payment" decimal(18,2) NOT NULL DEFAULT 0,
  "max_payment_time" timestamptz DEFAULT NULL,
  CONSTRAINT fk_bookings_product_id FOREIGN KEY ("product_id") REFERENCES "core"."products" ("id"),
  CONSTRAINT fk_bookings_user FOREIGN KEY ("user_id") REFERENCES "user"."users" ("id")
);
